#!/usr/bin/env php
<?php

/**
 * This file is part of the Cubiche/cqt project.
 */

// installed via composer?
if (file_exists($a = __DIR__.'/../../autoload.php')) {
    require_once $a;
} else {
    require_once __DIR__.'/vendor/autoload.php';
}

use Cubiche\Tools\CodeStyle\CSFixApplication;

$application = new CSFixApplication();
$application->run();
