#!/usr/bin/env php

<?php

/**
 * This file is part of the Jadddp/code-quality-tools project.
 */
 
set_time_limit(0);

// installed via composer?
if (file_exists($a = __DIR__.'/../../autoload.php')) {
    require_once $a;
} else {
    require_once __DIR__.'/vendor/autoload.php';
}

$application = new CodeQualityTool();
$application->run($input);
